eu_cards = {
monsters: [
  {title: "Goblin", text: ""},
  {title: "Orc", text: ""},
  {title: "Fimir", text: ""},
  {title: "Skeleton", text: ""},
  {title: "Zombie", text: ""},
  {title: "Mummy", text: ""},
  {title: "Chaos Warrior", text: ""},
  {title: "Gargoyle", text: ""},
],
treasure: [
  {title: "Gem!", text: "Tucked into the toe of an old boot you find a valuable Gem. The stone is worth 50 gold coins. Record the money on the back of your character sheet.", image: ""},
  {title: "Gold!", text: "A meagre haul of just 10 gold coins is found in the pocket of a smelly, worn jerkin. Record the money on the back of your character sheet.", image: "gold_eu"},
  {title: "Gold!", text: "A rummage through several items of clothing reveals 20 gold coins. Record the money on the back of your character sheet.", image: "gold_eu"},
  {title: "Gold!", text: "Amidst the clutter, the old rags, the greasy fur robes and soiled blankets, you find 25 gold coins. Record the money on the back of your character sheet.", image: "gold_eu"},
  {title: "Gold!", text: "Foolishly left unhidden lies a small box containing 25 gold coins. Record the money on the back of your character sheet.", image: "gold_eu"},
  {title: "Gold!", text: "You find a loose stone behind which is hidden a small leather pouch wrapped in an old rag. You look inside the pouch and find 50 gold coins. Record the money on the back of your character sheet.", image: "gold_eu"},
  {title: "Gold!", text: "You search and find small amounts of gold hidden in several places. But you lose track of time. Roll one die and multiply the result by ten to see how many gold coins you find. Miss your next go. Record the money on the back of your character sheet.", image: "gold_eu"},
  {title: "Trap!", text: "As you search you unwittingly set off a trap. An arrow shoots out from the wall. You must lose one body point. Return this card to the treasure pile.", image: "hazard1"},
  {title: "Trap!", text: "You feel the gentle pressure of a trip wire against your leg, you spin round … but it is too late. You lose one body point from the crossbow bolt that shoots from the wall. Return this card to the treasure pile.", image: "trap03"},
  {title: "Trap!", text: "The stone beneath your foot begins to give way and all too late you realize it is a trap. You fall into a pit and lose one Body point. You may climb out and move as normal on your next turn. The pit then closes. Return this card to the treasure pile.", image: "hazard2"},
  {title: "Heroic Brew", text: "A leather bag hanging on the wall contains a potion. It is a Heroic Brew. The potion may be taken just before you are about to attack. Any player who drinks the potion will be able to make two attacks instead of one, for one turn only. The card is then discarded.", image: ""},
  {title: "Holy Water", text: "Discarded and forgotten in a corner of the room you find a vial of Holy Water. You may use the Holy Water instead of attacking. It will kill any undead creature: Skeleton, Zombie, Mummy. Discard after use.", image: ""},
  {title: "Jewels!", text: "You find a small wooden box. The box is plain and old but within … it is lined with velvet and contains 50 gold coins' worth of jewels. Record the money on the back of your character sheet.", image: ""},
  {title: "Nothing", text: "Despite a thorough search you find nothing.", image: ""},
  {title: "Potion of Resilience", text: "Amidst a collection of old bottles and earthen jugs you find a small clear vial, a Potion of Resilience. It may be taken at any time. You may then roll two extra combat dice in defence when you next defend. The card is then discarded.", image: "potionofstrength"},
  {title: "Potion of Healing", text: "Enveloped in a bundle of rags you find a small bottle of liquid. You recognise it as a healing potion. You may drink the potion at any time. It will restore up to four lost Body points. The card is then discarded.", image: ""},
  {title: "Potion of Speed", text: "Standing on a shelf you see a dusty bottle. As you wipe it clean, you realize it is a potion of speed. You may drink the potion at any time. It will allow you to roll twice as many dice as usual the next time you move. The card is then discarded.", image: ""},
  {title: "Potion of Strength", text: "You find a small purple bottle. It is a Potion of Strength. You may drink the potion at any time. It will enable you to roll two extra combat dice in attack in your next attack. The card is then discarded.", image: ""},
  {title: "Treasure Horde!", text: "Luck is with you. A small treasure chest you find, hidden under an old fur, contains 100 gold coins. Record the money on the back of your character sheet.", image: ""},
  {title: "Wandering Monster", text: "As you are busy searching, a monster stalks up on you and attacks. The Evil Wizard player may place the wandering monster shown in the Quest Book for this adventure in any square next to you. The monster attacks immediately. Return this card to the treasure pile.", image: ""},
],
artifacts: [
  {title: "Borin's Armour", text: "Borin's Armour allows you to roll four combat dice in defence.", image: ""},
  {title: "Orcs Bane", text: "The sword, Orcs Bane allows you to roll two combat dice in attack. You may attack TWICE if you are fighting Orcs.", image: ""},
  {title: "Spirit Blade", text: "Spirit Blade allows you to roll three combat dice in attack OR four dice in attack against undead creatures: Skeletons, Zombies and Mummies.", image: ""},
  {title: "Talisman of Lore", text: "The Talisman allows you to increase your Mind points by two as long as you have the Talisman in your possession.", image: ""},
  {title: "Wand of Recall", text: "The Wand of Recall allows you to cast two spells instead of one during your turn.", image: ""},
],
equipment: [
  {title: "Battle axe", text: "The Battle axe allows you to roll four combat dice in attack. You may not use a shield when using the Battle axe.", image: "", cost: 400, wizard: false, type: "weapon"},
  {title: "Bracers", text: "The Bracers allows you to roll one extra combat die in defence.", image: "", cost: 200, wizard: true, type: "armour"},
  {title: "Broadsword", text: "The Broadsword allows you to roll three combat dice in attack.", image: "", cost: "250", wizard: false, type: "weapon"},
  {title: "Chain Mail", text: "Chain mail armour allows you to roll three combat dice in defence.", image: "", cost: "450", wizard: false, type: "armour"},
  {title: "Cloak of Protection", text: "The cloak allows you to roll one extra die in defence.", image: "", cost: "350", wizard: true, type: "armour"},
  {title: "Crossbow", text: "The Crossbow allows you to roll three combat dice in attack. You may not use the Crossbow against an opponent who is adjacent to you.", image: "", cost: "350", wizard: false, type: "weapon"},
  {title: "Hand axe", text: "The Hand axe allows you to roll two combat dice in attack. You may also throw the Hand axe but if you do so you lose it.", image: "", cost: "150", wizard: false, type: "weapon"},
  {title: "The Helmet", text: "The helmet gives you one extra combat die in defence.", image: "helmet", cost: "120", wizard: false, type: "armour"},
  {title: "Plate armour", text: "Plate armour allows you to roll four combat dice in defence, BUT You may only roll one die for movement whilst wearing plate armour.", image: "", cost: "850", wizard: false, type: "armour"},
  {title: "The shield", text: "The shield gives you one extra combat die in defence.", image: "shield", cost: "100", wizard: false, type: "armour"},
  {title: "Short sword", text: "The Short sword allows you to roll two combat dice in attack. The Short sword may be used to attack diagonally.", image: "", cost: "150", wizard: false, type: "weapon"},
  {title: "Spear", text: "The Spear allows you to roll two combat dice in attack. The Spear may be used to attack diagonally. You may also throw the Spear but if you do so you lose it.", image: "", cost: "150", wizard: false, type: "weapon"},
  {title: "Staff", text: "The Staff allows you to roll two combat dice in attack. The Staff may be used to attack diagonally.", image: "", cost: "100", type: "weapon"},
  {title: "Tool kit", text: "The tool kit enables you to remove any trap that you find. Roll one combat die. On the roll of a skull the trap goes off and you lose one Body point. Once you have rolled the die the trap is removed.", image: "", cost: "250"},
],
airspells: [
  {title: "Genie", text: "This spell conjures up a Genie who will do one of the following: open any door on the board (the room's contents should be put out) OR attack anyone on the board. He will attack only once with five combat dice. The spell is then discarded.", image: ""},
  {title: "Swift Wind", text: "This spell may be cast on any one player. That player may then roll twice as many dice as normal the next time he moves. The spell is then discarded.", image: ""},
  {title: "Tempest", text: "A small Tempest is created which envelops one monster or player of your choice. That monster or player will then miss his next turn. The spell is then discarded.", image: ""},
],
earthspells: [
  {title: "Heal Body", text: "This spell may be cast on any one player. It will restore up to four Body points that have been lost. The spell is then discarded.", image: ""},
  {title: "Pass through Rock", text: "This spell may be cast on any one player. That player may then move through walls when he next moves. The player may move through as many walls as his movement will allow. The spell is then discarded.", image: ""},
  {title: "Rock Skin", text: "This spell may be cast on any one player. That player may then throw two extra combat dice in defence, until the spell is broken. The spell is broken when that player is wounded. The spell is then discarded.", image: ""},
],
firespells: [
  {title: "Ball of Flame", text: "This spell may be cast at any one monster or player. It will inflict two points of Body damage. The victim may roll two dice. For each shield he rolls he may reduce the damage by one. The spell is then discarded.", image: ""},
  {title: "Courage", text: "This spell may be cast on any one player. That player may then throw two extra dice each time he attacks, until the spell is broken. The spell is broken when there are no more monsters visible to that player. The spell is then discarded.", image: ""},
  {title: "Fire of Wrath", text: "This spell may be cast on any one monster or player, anywhere on the board. It will seek out your enemy and inflict one Body point of damage, unless your opponent can roll a shield on one combat die. The spell is then discarded.", image: ""},
],
waterspells: [
  {title: "Sleep", text: "This spell will put one monster or player to sleep. He may try to defend himself by rolling one die per Mind point. If he rolls a shield he is unaffected. Once asleep he may not defend if attacked. He will awake if he rolls a six at the start of his turn, or if attacked.", image: ""},
  {title: "Veil of Mist", text: "This spell may be cast on any one player. That player may then move unseen through spaces that are occupied by other players or monsters the next time he moves. The spell is then discarded.", image: ""},
  {title: "Water of Healing", text: "This spell may be cast on any one player. It will restore up to four Body points that have been lost. The spell is then discarded.", image: ""},
],
};
us_cards = {
monsters: [
  {title: "Goblin", text: ""},
  {title: "Orc", text: ""},
  {title: "Fimir", text: ""},
  {title: "Skeleton", text: ""},
  {title: "Zombie", text: ""},
  {title: "Mummy", text: ""},
  {title: "Chaos Warrior", text: ""},
  {title: "Gargoyle", text: ""},
],
equipment: [
  {title: "Battle Axe", text: "This heavy, double-edged axe gives you the attack strength of 4 combat dice. You may not use a shield when using this weapon.", image: "", cost: "450", wizard: false, type: "weapon"},
  {title: "Broadsword", text: "This wide blade gives you the attack strength of 3 combat dice.", image: "", cost: "250", wizard: false, type: "weapon"},
  {title: "Chain Mail", text: "This light metal armor gives you 1 extra combat die in defense. May be combined with the Helmet and/or Shield.", image: "", cost: "500", wizard: false, type: "armor"},
  {title: "Crossbow", text: "This long-range weapon gives you the attack strength of 3 combat dice. You may fire at any Monster that you can “see.” However, you cannot fire at a Monster that is adjacent to you. You have an unlimited supply of arrows.", image: "", cost: "350", wizard: false, type: "weapon"},
  {title: "Dagger", text: "This sharp knife gives you the attack strength of 1 combat die. A dagger can also be thrown at any Monster that you can “see,” but is lost once it is thrown.", image: "", cost: "25", type: "weapon"},
  {title: "Helmet", text: "This protective headpiece gives you 1 extra combat die in defense.", image: "", cost: "125", wizard: false, type: "armor"},
  {title: "Longsword", text: "This long blade gives you the attack strength of 3 combat dice. Because of its length, the longsword enables you to attack diagonally.", image: "broadsword", cost: "350", wizard: false, type: "weapon"},
  {title: "Plate Mail", text: "This heavy metal armor gives you 2 extra combat dice in defense. However, because it is so heavy, you may only roll 1 red die for movement while wearing it. May be combined with the Helmet and/or Shield.", image: "platearmour", cost: "850", wizard: false, type: "weapon"},
  {title: "Shield", text: "This hand-held armor gives you 1 extra combat die in defense. May not be used with the Battle Axe or the Staff.", image: "", cost: "150", wizard: false, type: "armor"},
  {title: "Shortsword", text: "This short blade gives you the attack strength of 2 combat dice.", image: "", cost: "150", wizard: false, type: "weapon"},
  {title: "Staff", text: "This long, sturdy, wooden staff gives you the attack strength of 1 combat die. Because of its length, the staff enables you to attack diagonally. You may not use a shield when using this weapon.", image: "", cost: "100", type: "weapon"},
  {title: "Tool Kit", text: "Disarm Traps This tool kit gives you a 50% chance to disarm any searched-for-and-found (but unsprung) trap. See rulebook for correct procedure. Before you move, you must announce that you are moving onto the trap square to attempt to disarm and remove the trap. Roll one Combat Die. If a Skull is rolled, the trap is sprung. If a White or Black Shield is rolled, the trap is disarmed and gone forever.", image: "", cost: "250"},
],
artifacts: [
  {title: "Borin's Armor", text: "This magical suit of plate mail allows the wearer to roll four combat dice in defense. Unlike normal plate mail, this mysterious, ultralight metal armor does not slow down its wearer.", image: "", wizard: false, image: "borinsarmour"},
  {title: "Elixir of Life", text: "This small bottle of pearly liquid will bring a dead Hero back to life, restoring all of his Body and Mind Points. This potion can only be used once.", image: ""},
  {title: "Orc's Bane", text: "When using this magical shortsword, you roll two combat dice to attack. You may attack twice if attacking an Orc.", image: "", wizard: false},
  {title: "Ring of Return", text: "When invoked, this magical ring will return all Heroes that the ring wearer can \"see\" to the starting point of the Quest. It can only be used once.", image: ""},
  {title: "Spell Ring", text: "This ring enables the Wizard or Elf to cast one spell two times (not simultaneously). At the beginning of a Quest, the wearer of this ring must declare which of his spells he is storing in the ring.", image: ""},
  {title: "Spirit Blade", text: "This magical broadsword has an eerie handle of carved bone. When using it, roll three combat dice to attack, or roll four combat dice if attacking an undead monster (Skelton, Zombie, or Mummy).", image: "", wizard: false},
  {title: "Talisman of Lore", text: "This magical medallion increases your Mind Points by 1 for as long as it is worn.", image: ""},
  {title: "Wand of Magic", text: "This magical wand allows the Elf or Wizard to cast two separate and different spells on his turn instead of one single spell.", image: ""},
  {title: "Wizard's Cloak", text: "This magical cloak made of shimmery fabric is covered with mystical runes. It can be worn only by the Wizard, giving him one extra combat die in defense.", image: ""},
  {title: "Wizard's Staff", text: "This long ancient staff glows with a soft blue light. It can be used only by the Wizard, giving him the attack strength of two combat dice and the ability to strike diagonally.", image: ""},
],
treasure: [
  {title: "Gem!", text: "Tucked into the toe of an old boot you find a small gem worth 35 gold coins. Record the money on your sheet. Do not return this card to the deck.", image: ""},
  {title: "Gold!", text: "Amidst old rags, tattered fur robes and soiled blankets, you find a collection of 15 gold coins. Record the money on your sheet. Do not return this card to the deck.", image: ""},
  {title: "Gold!", text: "You find a loose stone and tear it from the wall. Behind it you discover a small leather pouch wrapped in an old rag. Peering inside, you find 25 gold coins. Record the money on your sheet. Do not return this card to the deck.", image: ""},
  {title: "Hazard!", text: "While you are searching, a hidden arrow shoots from the wall striking you. You lose 1 Body Point and your turn is over. Return this card to the bottom of the deck.", image: "hazard1"},
  {title: "Hazard!", text: "Suddenly, the stone beneath your feet gives way. You fall into a shallow hole, losing 1 Body Point and ending your turn. You may climb out and move normally on your next turn. Return this card to the bottom of the deck.", image: "hazard2"},
  {title: "Heroic Brew", text: "You are surprised to find a leather bag hanging on the wall. If you drink its contents before you attack, you can make two attacks instead of one. This may only be used once. Do not return this card to the deck.", image: ""},
  {title: "Jewels!", text: "You find a small wooden box. It is simple-looking and very old. Within you discover that it is lined with velvet and contains very small jewels worth 50 gold coins. Record the money on your sheet. Do not return this card to the deck.", image: ""},
  {title: "Potion of Defense", text: "Amidst a collection of old bottles, you find a small vial containing a clear liquid. You can drink this potion at any time, giving you two extra combat dice the next time you defend. This may only be used once. Do not return this card to the deck.", image: ""},
  {title: "Potion of Healing", text: "In a bundle of rags, you find a small bottle of bluish liquid. You can drink this healing potion at any time, restoring the number of Body Points equal to a roll of one red die. You cannot, however, exceed your starting number of Body Points. This may only be used once. Do not return this card to the deck.", image: ""},
  {title: "Potion of Strength", text: "You find a small purple flask. You can drink this strange smelling liquid at any time, enabling you to roll two extra combat dice the next time you attack. This may only be used once. Do not return this card to the deck.", image: ""},
  {title: "Wandering Monster", text: "As you are searching, a monster stalks you and attacks! Zargon places the wandering monster (listed in the Quest Book) on any square next to you. The monster attacks immediately! Return this card to the bottom of the deck.", image: ""},
],
chaosspells: [
  {title: "Ball of Flame", text: "This spell can be cast on any one Hero. It will inflict 2 Body Points of damage. The Hero immediately rolls two red dice. For each 5 or 6 rolled, the damage is reduced by 1 point.", image: ""},
  {title: "Cloud of Chaos", text: "This spell paralyzes all Heroes located in the same room or corridor. A paralyzed Hero is unable to move, attack, or defend himself. The spell can be broken at once or on a future turn by each victim rolling one red die for each of his Mind Points. By rolling a 6, the Hero frees himself.", image: ""},
  {title: "Command", text: "This spell puts any one Hero under Zargon's control. The spell can be broken immediately or on a future turn by the Hero rolling one red die for each of his Mind Points. If a 6 is rolled, the spell is broken. However, until the spell is broken, Zargon, on his turn, can move the Hero as a monster and attack other Heroes.", image: ""},
  {title: "Escape", text: "This spell allows the spellcaster to disappear and instantly teleport to a secret destination known only to Zargon. This \"safe place\" is marked on the Quest Map.", image: ""},
  {title: "Fear", text: "This spell causes any one Hero to become so fearful that his attacks are reduced to one combat die. The spell can be broken by the Hero on a future turn by rolling one red die for each of his Mind Points. If a 6 is rolled, the spell is broken.", image: ""},
  {title: "Firestorm", text: "This spell creates a roomful of fire that inflicts 3 Body Points of damage on all Heroes and monsters in the same room with the spellcaster. The spellcaster is unaffected. All victims immediately roll two red dice. For each 5 or 6 rolled, the damage is reduced by 1 point. Not used in corridors.", image: ""},
  {title: "Lightning Bolt", text: "This spell may be cast in a horizontal, vertical, or diagonal direction. The bolt will travel in a straight line until it strikes a wall or closed door. It will inflict 2 points of Body damage on all Heroes or monsters that stand in its path.", image: "lightning"},
  {title: "Rust", text: "This spell causes any one metal sword or helmet to become so thin, brittle and useless that it can never be used again. Not effective against Artifacts.", image: ""},
  {title: "Sleep", text: "This spell puts any one Hero into a deep sleep. A sleeping Hero is unable to move, attack, or defend himself. The spell can be broken immediately or on a future turn by the Hero rolling one red die for each of his Mind Points. If a 6 is rolled, the spell is broken.", image: ""},
  {title: "Summon Orcs", text: "This spell conjures up a group of Orcs to surround and protect the spellcaster. Roll one red die:<br/>Roll a 1, 2 or 3 = 4 Orcs<br/>Roll a 4 or 5 = 5 Orcs<br/>Roll a 6 = 6 Orcs", image: ""},
  {title: "Summon Undead", text: "This spell conjures up a group of undead to surround and protect the spellcaster. Roll one red die:<br/>Roll a 1 or 2 = 4 Skeletons<br/>Roll a 3 or 4 = 3 Skeletons, 2 Zombies<br/>Roll a 5 or 6 = 2 Zombies, 2 Mummies", image: ""},
  {title: "Tempest", text: "This spell creates a small whirlwind that envelops one Hero of your choice. That Hero will then miss his next turn.", image: ""},
],
airspells: [
  {title: "Genie", text: "This spell conjures up a Genie who will do one of the following: open any door on the board (revealing what lies beyond) OR use 5 combat dice to attack any monster within your line of sight.", image: ""},
  {title: "Swift Wind", text: "This spell may be cast on any one Hero, including yourself. Its powerful burst of energy enables that Hero to roll twice as many red dice as normal the next time he moves.", image: ""},
  {title: "Tempest", text: "This spell creates a small whirlwind that envelops one monster of your choice. That monster will then miss its next turn.", image: ""},
],
earthspells: [
  {title: "Heal Body", text: "This spell may be cast on any one Hero, including yourself. Its magical power will immediately restore up to 4 lost Body Points, but does not give a Hero more than his starting number.", image: ""},
  {title: "Pass Through Rock", text: "This spell can be cast on any one Hero, including yourself. That Hero may then move through walls on his next move. He may move through as many walls as his dice roll allows. Caution! There are shaded areas on each Quest Map which indicate solid rock. If a Hero ends his move in one of these areas, he is trapped forever!", image: ""},
  {title: "Rock Skin", text: "This spell may be cast on any one Hero, including yourself. That Hero may throw one extra combat die when defending. The spell is broken when the Hero suffers 1 point of Body damage.", image: ""},
],
firespells: [
  {title: "Ball of Flame", text: "This spell may be cast on any one monster, enveloping it in a ball of fire. It will inflict 2 Body Points of damage. The monster then rolls two red dice. For each 5 or 6 rolled, the damage is reduced by 1 point.", image: ""},
  {title: "Courage", text: "This spell may be cast on any one Hero, including yourself. The next time that Hero attacks, he may roll two extra combat dice. The spell is broken the moment the Hero can no longer \"see\" a monster.", image: ""},
  {title: "Fire of Wrath", text: "This spell may be cast on any one monster, blasting it with flames. It will inflict 1 Body Point of damage, unless the monster can immediately roll a 5 or 6 using one red die.", image: ""},
],
waterspells: [
  {title: "Sleep", text: "This spell puts a monster into a deep sleep so it cannot move, attack, or defend itself. The spell can be broken at once or on a future turn by a monster rolling one red die for each of its Mind Points. If a 6 is rolled, the spell is broken. May not be used against Mummies, Zombies or Skeletons.", image: ""},
  {title: "Veil of Mist", text: "This spell may be cast on any one Hero, including yourself. On the Hero's next move, he may move unseen through spaces that are occupied by monsters.", image: ""},
  {title: "Water of Healing", text: "This spell may be cast on any one Hero, including yourself. Contact with this revitalizing water will restore up to 4 lost Body Points, but will not give a Hero more than his starting number.", image: ""},
],
};
kk_cards = {
artifacts: [
  {title: "Fire Ring", text: "Protects the wearer from any 2 Chaos fire spells. Ring disappears after wearer has been protected from the second fire spell.", image: ""},
  {title: "Magical Throwing Dagger", text: "Always inflicts 1 Body Point of damage when thrown at a monster a Hero can \"see.\" Monster cannot defend. Dagger is lost once it is thrown.", image: ""},
  {title: "Ball of Flame", text: "This spell may be cast on a monster, enveloping it in a ball of fire. It will inflict 2 Body Points of damage. The monster then rolls two red dice. For each 5 or 6 rolled, the damage is reduced by 1 point. May be used by any Hero. Scroll crumbles to dust after it is used.", image: "", type: "scroll"},
  {title: "Courage", text: "This spell may be cast on a Hero, including yourself. The next time that Hero attacks, he may roll two extra combat dice. The spell is broken the moment the Hero can no longer \"see\" a monster. May be used by any Hero. Scroll crumbles to dust after it is used.", image: "", type: "scroll"},
  {title: "Fire of Wrath", text: "This spell may be cast on a monster, blasting it with flames. It will inflict 1 Body Point of damage, unless the monster can immediately roll a 5 or 6 using one red die. May be used by any Hero. Scroll crumbles to dust after it is used.", image: "", type: "scroll"},
  {title: "Genie", text: "This spell conjures up a Genie who will do one of the following: open any door on the gameboard (revealing what lies beyond), OR use five combat dice to attack a monster within your line of sight. May be used by any Hero. Scroll crumbles to dust after it is used.", image: "", type: "scroll"},
  {title: "Heal Body", text: "This spell may be cast on a Hero, including yourself. Its magical power will immediately restore up to 4 lost Body Points, but does not give a Hero more than his starting number. May be used by any Hero. Scroll crumbles to dust after it is used.", image: "", type: "scroll"},
  {title: "Rock Skin", text: "This spell may be cast on a Hero, including yourself. That Hero may roll one extra combat die when defending. The spell is broken when the Hero suffers 1 Body Point of damage. May be used by any Hero. Scroll crumbles to dust after it is used.", image: "", type: "scroll"},
  {title: "Sleep", text: "This spell puts a monster into a deep sleep so it cannot move, attack, or defend itself. The spell can be broken at once or on a future turn by a monster rolling one red die for each of its Mind Points. If a 6 is rolled, the spell is broken. May not be used against Mummies, Zombies or Skeletons. May be used by any Hero. Scroll crumbles to dust after it is used.", image: "", type: "scroll"},
  {title: "Tempest", text: "This spell may be cast on a monster, surrounding it with a small whirlwind. That monster will then miss its next turn. May be used by any Hero. Scroll crumbles to dust after it is used.", image: "", type: "scroll"},
],
}
rotwl_cards = {
artifacts: [
  {title: "Anti-poison Quill", text: "Restores any of the owner’s Body Points lost by poisoning if used immediately. May only be used once.", image: ""},
  {title: "Armband of Healing", text: "Restores 2 lost Body Points once per Quest. If the wearer’s Body Points are reduced to zero, use immediately to restore 2 Body Points.", image: ""},
  {title: "Dust of Disappearance", text: "If tossed on any Hero, this dust allows that Hero to move past any monsters encountered on his next turn. May only be used once.", image: ""},
  {title: "Magical Throwing Dagger", text: "Always inflicts 1 Body Point of damage when thrown at a monster a Hero can \"see.\" Monster cannot defend. Dagger is lost once it is thrown.", image: ""},
  {title: "Rabbit Boots", text: "To jump over 1 discovered trap per turn, roll anything but a Black Shield on 1 combat die.", image: ""},
  {title: "Ball of Flame", text: "This spell may be cast on a monster, enveloping it in a ball of fire. It will inflict 2 Body Points of damage. The monster then rolls two red dice. For each 5 or 6 rolled, the damage is reduced by 1 point. May be used by any Hero. Scroll crumbles to dust after it is used.", image: "", type: "scroll"},
  {title: "Courage", text: "This spell may be cast on a Hero, including yourself. The next time that Hero attacks, he may roll two extra combat dice. The spell is broken the moment the Hero can no longer \"see\" a monster. May be used by any Hero. Scroll crumbles to dust after it is used.", image: "", type: "scroll"},
  {title: "Fire of Wrath", text: "This spell may be cast on a monster, blasting it with flames. It will inflict 1 Body Point of damage, unless the monster can immediately roll a 5 or 6 using one red die. May be used by any Hero. Scroll crumbles to dust after it is used.", image: "", type: "scroll"},
  {title: "Genie", text: "This spell conjures up a Genie who will do one of the following: open any door on the gameboard (revealing what lies beyond), OR use five combat dice to attack a monster within your line of sight. May be used by any Hero. Scroll crumbles to dust after it is used.", image: "", type: "scroll"},
  {title: "Pass Through Rock", text: "This spell may be cast on a Hero, including yourself. That Hero may then move through walls on his next move. He may move through as many walls as his dice roll allows. Caution! There are shaded areas on each Quest Map which indicate solid rock. If a Hero ends his move in one of these areas, he is trapped forever! May be used by any Hero. Scroll crumbles to dust after it is used.", image: "", type: "scroll"},
],
}

atoh_cards = {
monsters: [
  {title: "Ogre Warrior", text: ""},
  {title: "Ogre Champion", text: ""},
  {title: "Ogre Chieftain", text: ""},
  {title: "Ogre Lord", text: ""},
],
chaosspells: [
  {title: "Dominate", text: "The Chaos Sorcerer and defender both roll dice equal to their Mind Points.  If the Sorcerer scores two skulls or more, he may use the defender's combat piece for the duration of his turn.", image: "mindblast"},
  {title: "Mind Blast", text: "The Chaos Sorcerer and defender both roll dice equal to their Mind Points.  The player who scores the most skulls inflicts Mind Point damage equal to the number of skulls he has in excess of his opponent's score."},
  {title: "Mind Lock", text: "The Chaos Sorcerer and defender both roll dice equal to their Mind Points.  The defender will be frozen for one turn for each skull scored by the Chaos Sorcerer.", image: "mindblast"},
],
}
wom_cards = {
highmagespells: [
  {title: "Dispell", text: "The Sorcerer may pick one spell using character and force them to discard one of their spell cards at random. That card is then lost for the duration of the Quest."},
  {title: "Escape", text: "The Sorcerer may use this spell to move instantly to any unoccupied square on the game board."},
  {title: "Madness", text: "Cast this spell on one figure to affect it with a frightening madness. Zargon may move that figure on his next turn, although the affected figure may not attack or cast spells."},
  {title: "Rust", text: "This spell causes on item of equipment of Zargon’s choice to rust and become useless. That piece of equipment should be crossed off the Hero’s character sheet."},
  {title: "Strands of Binding", text: "The Sorcerer may fire threads from their fingers, which will entangle one figure. The figure may not move or attack until they destroy the Strands of Binding, which have two Body Points and roll four Combat Dice in Defence. The figure may defend against other attacks."},
  {title: "Wall of Flame", text: "The Sorcerer creates a magical Wall of Flame, which covers two squares. The Wall has 2 Body Points and rolls 6 Combat Dice in Defence."},
],
necromancerspells: [
  {title: "Call Skeleton", text: "This spell summons two Skeletons, which appear immediately anywhere within sight of the Sorcerer. They may move and attack at once."},
  {title: "Death Bolt", text: "The Sorcerer may hurl this spell at one figure in sight. That figure then automatically loses one Body Point."},
  {title: "Fear", text: "The target of this spell is filled with unreasonable terror and may not attack or cast spells on their next turn, although they may still move and defend."},
  {title: "Raise the Dead", text: "Cast this spell on another player’s turn after a Monster has been killed. The Monster is then replaced with a Skeleton, which can move and attack immediately."},
  {title: "Skulls of Doom", text: "This spell allows a Sorcerer to hurl a magical skull at any figure in their line of sight. The skull explodes like a fireball and attacks the figure with two Combat Dice, which the figure may defend against normally."},
  {title: "Summon Mummy", text: "This spell summons a Mummy, which will appear on any square adjacent to the Sorcerer. The Mummy may move and attack at once."},
],
orcshamanspells: [
  {title: "Orc Berserker", text: "The Sorcerer may choose one Orc within their line of sight to be filled with immense strength and vigour. That Orc may then move twice and attack twice during this turn only."},
  {title: "Sharpen Blades", text: "This spell allows all Orcs in the same room as the Sorcerer to roll an extra Combat Die in attack for this turn only. This spell may not be used in corridors."},
  {title: "Shield of Protection", text: "This spell allows the Sorcerer and all Orcs in the same room to roll one extra Combat Die in defence until the beginning of the Sorcerer’s next turn. This spell may not be used in corridors."},
  {title: "Spirit of Vengeance", text: "This spell allows the Sorcerer to send an invisible spirit to attack any one figure on the board. The spirit attacks the figure with four Combat Dice, which the figure may defend against normally. The spirit then vanishes. The spirit itself cannot be harmed."},
  {title: "Summon Goblins", text: "The Sorcerer may immediately take four Goblin figures from anywhere on or off the game board and place them anywhere within the Sorcerer’s line of sight. The Goblins may move and attack immediately, unless they have already done so this turn."},
  {title: "Summon Orcs", text: "The Sorcerer may immediately take two Orc figures from anywhere on the game board and place them within the Sorcerer’s line of sight. The Orcs may move and attack immediately, unless they have already done so this turn."},
],
spellsofdarkness: [
  {title: "Arrows of the Night", text: "This spell may be cast on any Monster within your line of sight. These magical bolts will inflict two Combat Dice of damage, which the Monster may defend against by rolling one Combat Die for each of their Mind Points."},
  {title: "Chains of Darkness", text: "This spell may be cast on any one Monster within your line of sight. That Monster may not move or attack until the beginning of your (the spell caster’s) next turn, although the Monster may still defend or cast spells."},
  {title: "Cloak of Shadows", text: "This spell summons a shroud of darkness. Place the Cloak of Shadows tile on the game board. Any figure in the shadows may not attack, be attacked or cast spells while they are there. The Cloak of Shadows may not be moved and lasts until the end of the Quest. Place this card beside the game board for reference."},
],
spellsofdetection: [
  {title: "Clairvoyance", text: "When casting this spell you may ask Zargon to lay out the contents of any one room on the game board at once. If that room is empty you may not try again."},
  {title: "Future Sight", text: "This spell may be cast on any one Hero, including yourself. That Hero may then re-roll any attack, defence, or movement die rolls once until the end of your (the spell caster’s) next turn."},
  {title: "Treasure Horde", text: "This spell may be cast on any one Hero, including yourself. That Hero may then draw three treasure cards the next time they search for treasure. They must take all three cards, whatever they are."},
],
spellsofprotection: [
  {title: "Dispell", text: "This spell may be cast on any spell-using figure. Choose any one of that figure’s unused spells at random and discard it. That spell is then lost for the duration of the Quest."},
  {title: "Invisibility", text: "This spell may be cast on any one Hero, including yourself. That Hero may become invisible and move around unseen until the beginning of your (the spell caster’s) next turn. While invisible, they may not attack, be attacked, or be affected by spells."},
  {title: "Wall of Stone", text: "This spell creates a magical Wall of Stone, which covers two squares. This Wall has two Body Points and rolls six Combat Dice in Defence."},
],
stormmasterspells: [
  {title: "Blinding Sleet", text: "The Sorcerer may fill the room with Blinding Sleet. No one in the room may move, make ranged attacks or cast spells until the beginning of the Sorcerer’s next turn. Figures may only attack and defend if they are adjacent to another figure."},
  {title: "Earthquake", text: "The Sorcerer may split the ground asunder in a line of six squares. Lay the Earthquake tile on the board to determine who is affected. All those caught will suffer one Body Point of damage as if they have fallen into a Pit Trap."},
  {title: "Hurricane", text: "The Sorcerer may only cast this spell on one figure that is in a straight line in front of them. That figure is then forced back in a straight line of squares until they hit a wall, another figure, fall down a Pit Trap, or trigger another trap."},
  {title: "Lightning Bolt", text: "The Sorcerer may fire a Lightning Bolt in a straight line of six squares. Use the Lightning Bolt tile to determine who is hit. Every figure hit is attacked with three Combat Dice, which they may defend against normally."},
  {title: "Thieving Wind", text: "This spell may only be cast on one figure. That figure loses one piece of equipment chosen at random, which is then crossed off their character sheet."},
  {title: "Wall of Ice", text: "The Sorcerer creates a magical Wall of Ice, which covers two squares. The Wall has two Body Points and rolls six Combat Dice in Defence."},
],
treasure: [
  {title: "Magical Trap!", text: "As you are searching the room, you set off a Fireburst Trap. Place a Fireburst Token in the centre of the room and refer to the Magical Reference Chart for the effects of the trap. Return this card to the bottom of the deck.", image: "magicaltrap_x2"},
  {title: "Poison!", text: "You uncover a rusty brown flask filled with a liquid. You taste it and it turns out to be poison! You must roll one Combat Die: if you roll a Skull you lose one Body Point, otherwise you are unharmed. Return this card to the bottom of the deck."},
  {title: "Potion of Alchemy", text: "In the corner of the room you stumble upon a worn pot containing a dull paste. If you spread this paste over one item of equipment, it turns to gold and is worth 100 gold coins. That piece of equipment is then lost."},
  {title: "Potion of Charm", text: "Behind an old tile you find a gilded bottle filled with a gold liquid. Drink this entire potion between Quests when you want to hire Mercenaries. You will then be able to hire up to three Mercenaries for 25 less gold each."},
  {title: "Potion of Magical Aptitude", text: "You discover a vial of silvery liquid under a loose flagstone. If you are an Elf or Wizard, you may drink this potion at the beginning of your next turn.  You will now be able to cast two spells in that turn rather than one."},
  {title: "Potion of Magic Resistance", text: "You discover a red glass bottle in a shallow pit. If you drink the potion, you will be completely unharmed by the next magical fire attack to hit you, be it a spell or a Fireburst Trap.", image: "potionofmagicresistance2"},
  {title: "Potion of Magic Resistance", text: "You find a small bottle hidden beneath a rusty shield. You may drink this potion when a spell is cast on you and you may then ignore the effects of that spell."}],
menatarms: [
  {title: "The Crossbowman", text: "", image: "crossbowman"},
  {title: "The Halberdier", text: "", image: "halberdier"},
  {title: "The Scout", text: "", image: "scout"},
  {title: "The Swordsman", text: "", image: "swordsman"},
],
}

fh_cards = {
artifacts: [
  {title: "Amulet of the North", text: "This ancient magical item was made for Barbarian kings centuries ago. It may be worn only by a Barbarian. While worn, it adds 2 Body Points and 1 Mind Point to the Barbarian's totals."},
  {title: "Armband of Ice", text: "This powerful item grants its wearer immunity to Mind Freeze and Chill spells, plus immunity to damage from ice vaults and icy rivers for as long as it is worn. It also reduces the damage from an Ice Storm spell by 1 point, for the armband wearer only."},
  {title: "Ring of Warmth", text: "This artifact grants its wearer immunity to the Chill spell, as well as to the effects of ice vaults and icy rivers."},
  {title: "Snowshoes of Speed", text: "These magical snowshoes add 2 squares to a Hero's movement, and they also negate the effects of slippery ice for as long as they are worn. These can be used only on Quests in cold, icy regions."},
  {title: "Chill", text: "This spell causes 1 Body Point of damage to any monster adjacent to the spellcaster (though not diagonally adjacent). The victim cannot defend against the attack. Scroll crumbles to dust once used.", type: "scroll"},
  {title: "Ice Bridge", text: "This spell creates a permanent bridge of Magic Ice tiles that enables Heroes to cross over any pit, trap, chasm, crevasse, or icy square. Scroll crumbles to dust once used.", type: "scroll"},
  {title: "Ice Storm", text: "This spell creates a blizzard of ice that affects an area 2 squares wide by 2 squares long. Each monster and Hero in that area is attacked separately by the spellcaster with 3 combat dice. There is no chance to defend. Cannot be used in corridors. Scroll crumbles to dust once used.", type: "scroll"},
  {title: "Psychic Recovery", text: "This spell restores all lost Mind Points to the spellcaster or any one Hero the spellcaster chooses. Scroll crumbles to dust once used.", type: "scroll"},
  {title: "Skate", text: "This spell enables the spellcaster to move quickly through icy caverns and corridors. The spellcaster adds 6 to his red dice movement roll and may pass through monsters and Heroes during movement. The spell lasts only one turn. Scroll crumbles to dust once used.", type: "scroll"},
  {title: "Warmth", text: "This spell bestows a healing warmth on the spellcaster or any one Hero the spellcaster chooses. The warmth restores up to 3 lost Body Points. Scroll crumbles to dust once used.", type: "scroll"},
],
chaosspells: [
  {title: "Chill", text: "This spell causes 1 Body Point of damage to any one Hero or monster adjacent to the spellcaster (though not diagonally adjacent). The victim cannot defend against the attack."},
  {title: "Ice Storm", text: "This spell creates a blizzard of ice that affects an area 2 squares wide by 2 squares long. Each monster and Hero in that area is attacked separately by the spellcaster with 3 combat dice. There is no chance to defend. Cannot be used in corridors."},
  {title: "Ice Wall", text: "This spell creates up to 4 squares of solid ice. (Use the single-square Magic Ice tiles.) These squares block movement, but not line of sight. The squares need not be adjacent, but they must all be  within the line of sight of the spellcaster. Each ice square lasts until the spellcaster dies, cancels the spell, or can no longer see the square, or until a cumulative total of 5 skulls are rolled in attacks on the ice square."},
  {title: "Mind Freeze", text: "This spell ravages the mind of any Hero. The Hero rolls 1 combat die for every Mind Point he possessed before the attack. If 1 or more white shields are rolled, the Hero has 1 Mind Point left. If no white shields are rolled, the Hero has been reduced to zero Mind Points and goes into \"shock.\" (See the Mind Points section of the Barbarian Quest Book.)"},
  {title: "Skate", text: "This spell enables the spellcaster to move quickly through icy caverns and corridors. The spellcaster may skate for up to 12 squares and may pass through Heroes and monsters during movement. The spell lasts only one turn."},
  {title: "Soothe", text: "The healing coolness of this spell restores up to 3 lost Body Points to the spellcaster or any one monster."},
],
treasure: [
  {title: "Poison!", text: "You discover a brown flast filled with liquid. Your throat constricts as you taste it, and you realize you've swallowed poison! Roll 1 combat die; a skull means you lose 1 Mind Point. You are unharmed on any other roll. Return this card to the bottom of the deck."},
  {title: "Potion of Magic Resistance", text: "The potion in this small, blue bottle negates the effects of any damage-causing spell cast on you. Drink it when the spell is cast and you may ignore the effects of the spell. This works only for the Hero drinking the potion. This potion may be used only once."},
  {title: "Potion of Warmth", text: "This miniature jug is warm to the touch. Drinking the potion immediately after suffering damage from Ice Storm or Chill spells, or from ice vaults or icy rivers, restores 2 lost Body Points. Drinking it at any other time restores only 1 lost Body Point. This potion may be used only once."},
],
monsters: [
  {title: "Ice Gremlin", text: ""},
  {title: "Yeti", text: ""},
  {title: "Polar Warbear", text: ""},
  {title: "Frozen Horror", text: ""},
],
menatarms: [
  {title: "The Crossbowman", text: "", image: "crossbowman"},
  {title: "The Halberdier", text: "", image: "halberdier"},
  {title: "The Scout", text: "", image: "scout"},
  {title: "The Swordsman", text: "", image: "swordsman"},
],
}

mm_cards = {
artifacts: [
  {title: "Ancient Staff", text: "This magical staff enables the Elf to reflect any monster's spell back at the spellcaster. The spellcaster and all other monsters in the same room suffer the full effects of the spell, while the Elf and his companions are immune to the efftects. The staff works only 5 times, then it becomes useless."},
  {title: "Bone Wand", text: "This artifact enables any Hero to control all skeletons in one room for one turn. He can move them and make them attack during this turn. The Hero can make the skeletons attack each other or any other monsters in the room. The Bone Wand works only once per Quest."},
  {title: "Elven Boots", text: "These boots grant the Elf an extra red die for movement. The Elf can roll 3 dice for movement either before or after taking an action. The boots wear out if the Elf rolls identical numbers on any 3 dice."},
  {title: "Elven Bow of Vindication", text: "Only an Elf may use this bow. An arrow fired from this bow hits and instantly kills any one monster within the Elf's line of sight, unless the monster rolls a black shield on 1 combat die. There are only 4 arrows with this bow; the bow is useless once all of these arrows have been fired. This card can be used only in the Elf Quest Pack."},
  {title: "Elven Bracers", text: "These metallic wrist bands have magical powers. When placed on the Elf's wrists, these glowing artifacts greatly enhance the Elf's physical and mental abilities. The bracers add 2 extra Body Points and 1 extra Mind Point to the Elf's total. They can be  worn only by the Elf."},
  {title: "Sky Orb", text: "The Hero who possesses this orb may use it to absorb a total of 4 Mind Points of damage. Each time the Hero would normally suffer the loss of 1 Mind Point, he instead hands Zargon one of the blue Sky Orb tokens and suffers no Mind Point damage. When all 4 tokens have been handed to Zargon, the Sky Orb is useless."},
  {title: "Treasure Without Doom", text: "This spell scroll enables a Hero to pick cards from the treasure deck, ignoring all Wandering Monster and Hazard cards, until he picks a card showing gold, a potion, gems, or jewels. Or it can be used to open one chest without harm, disarming any trap on the chest. Scroll crumbles to dust after it is used.", type: "scroll"},
],
chaosspells: [
  {title: "Dispell", text: "This special spell may be cast by a Chaos spellcaster during a Hero's turn. It is used to try to cancel a spell cast by a Hero. The Dispell is cast immediately after the Hero casts a spell. First the Chaos spellcaster rolls 1 red die and adds the result to their Mind Points. Then the Hero does the same. If the Chaos spellcaster's total is higher, the Hero's spell has been cancelled."},
  {title: "Mind Blast", text: "This spell paralyzes one Hero within the spellcaster's line of sight. This Hero cannot move or attack. The Hero defends with 1 combat die. To break free of the spell, the Hero, on his turn, rolls 1 red die for every Mind Point he currently has. If a 6 is rolled on any die, the spell is broken and the Hero can move and attack normally again on future turns."},
  {title: "Mirror Magic", text: "This spell may be cast by a Chaos spellcaster during a Hero's turn. This enables the spellcaster to reflect any Hero's spell back to him. Mirror Magic is cast immediately after the Hero casts a spell at the Chaos spellcaster. The Hero then suffers the effect of the spell that was intended for the spellcaster."},
  {title: "Reanimation", text: "This spell enables the spellcaster to reanimate all defeated skeletons, zombies, or mummies in the same room as the spellcaster. These monsters rise up from the floor, with all lost Body Points restored, and attack the Heroes again."},
  {title: "Restore Chaos", text: "This spell may be cast only on monsters. It restores up to 6 lost Body Points to either the spellcaster or any monster within the spellcaster's line of sight."},
  {title: "Summon Wolves", text: "This spell conjures up a number of Giant Wolves to attack the spellcaster's enemies. (Place the Giant Wolves adjacent to the spellcaster.) To see how many Giant Wolves appear, roll 1 red die and check the result: 1 or 2 = 1 Giant Wolf 3 or 4 = 2 Giant Wolves 5 or 6 = 3 Giant Wolves"},
  {title: "Werewolf's Curse", text: "This spell may be cast on any Hero. The Hero rolls a red die. A roll of 6 means the spell has no effect. Any other result means the Hero is now afflicted with the Werewolf's Curse. See the \"Turning Heroes into Werewolves\" section of the Elf Quest Book for more information."},
],
elfspells: [
  {title: "Deep Sleep", text: "This spell may be cast on any monster within your line of sight, as long as the monster has from 1 to 3 Mind Points. The monster falls asleep immediately. It stays asleep until Zargon's next turn. The monster cannot defend against a Hero's attack while it is asleep."},
  {title: "Disappear", text: "This spell may be cast on a the spellcaster or on any one Hero he chooses. The Hero moves unseen as long as he rolls an 8 or lower on his movement dice. If a 9, 10, 11, or 12 is rolled, the spell ends. The Hero can only move and open doors. He cannot attack, search, disarm, cast spells, spring traps, or be affected by attacks or spells, unless he chooses to cancel the spell."},
  {title: "Double Image", text: "This spell may be cast on the spellcaster or on any one Hero the spellcaster chooses. It causes a life-like image of the Hero to appear. If an attack against the Hero is successful, he rolls 1 red die. On a 1, 2, or 3, the image was attacked and the Hero suffers no damage. The spell is broken the moment the Hero can no longer see a monster."},
  {title: "Flashback", text: "By casting this spell, the spellcaster or any one Hero the spellcaster chooses can replay his entire turn. All results of the Hero's first turn are canceled. You can cast this after any Hero's turn. Casting this spell does not count as your action for the turn."},
  {title: "Hypnotic Blaze", text: "When this spell is cast, an illusion of a huge, animated flame appears. Every figure in the room or corridor (except for the spellcaster) must roll 1 red die. A figure that rolls equal to or less than its Mind Points is unaffected by the illusion. Rolling a number greater than its Mind Points means that the figure is paralyzed for 3 turns - unable to move, attack, or defend."},
  {title: "Slow", text: "This spell reduces any one monster's movement to 1 square per turn. The monster also rolls 1 less combat die when it attacks or defends. The monster's movement and combat dice cannot be less than 1. These effects last until the monster is killed or is out of your line of sight."},
  {title: "Timestop", text: "This spell may be cast on the spellcaster or any one Hero the spellcaster chooses. It temporarily stops time for everyone else on the gameboard, enabling the Hero to take another turn immediately after his current turn."},
  {title: "Twist Wood", text: "This spell causes any wooden weapon, such as a staff, bow, or crossbow, to become warped into uselessness."},
],
treasure: [
  {title: "Air Walk", text: "This potion enables any Hero to walk on a cushion of air for one turn. He does not spring traps during this turn. The Hero can walk over pit traps as long as he can reach an unoccupied space on the other side. This may be used only once. Do not return this card to the deck."},
  {title: "Elven Cloak of Passage", text: "This cloak enables the Elf to pass through walls without harm. Caution! There are shaded areas on each Quest Map that indicate solid rock. If the Elf ends his move in one of these areas, he is trapped forever! This cloak works only three times. Discard after the third use."},
  {title: "Treasure Hoard!", text: "Under a loose stone in the floor, you find a small chest. Inside are 300 gold coins! Record the money on your Character Sheet. Do not return this card to the deck."},
  {title: "Wolfsbane Potion", text: "This may be used by any Hero suffering under the Werewolf's Curse. This potion cures the Hero of this curse. This may be used only once. Do not return this card to the deck."},
],
monsters: [
  {title: "Elven Archer", text: ""},
  {title: "Elven Warrior", text: ""},
  {title: "Giant Wolf", text: ""},
  {title: "Ogre", text: "", name: "OgreWarrior"},
],
}

sets = [
  {name: "Monsters", campaign: "GS", region: "EU", type: "monster", cards: eu_cards.monsters},
  {name: "Quest Treasure", campaign: "GS", region: "EU", type: "artifact", cards: eu_cards.artifacts},
  {name: "Air Spells", campaing: "GS", region: "EU", type: "airspell", cards: eu_cards.airspells},
  {name: "Earth Spells", campaign: "GS", region: "EU", type: "earthspell", cards: eu_cards.earthspells},
  {name: "Fire Spells", campaign: "GS", region: "EU", type: "firespell", cards: eu_cards.firespells},
  {name: "Water Spells", campaign: "GS", region: "EU", type: "waterspell", cards: eu_cards.waterspells},
  {name: "Treasure", campaign: "GS", region: "EU", type: "treasure", cards: eu_cards.treasure},
  {name: "Equipment", campaign: "GS", region: "EU", type: "equipment", cards: eu_cards.equipment},
  {name: "Against the Ogre Horde Chaos Spells (originally not on cards)", campaign: "AtOH", region: "EU", type: "chaos", cards: atoh_cards.chaosspells},
  {name: "Against the Ogre Horde Monsters (originally inside the booklet)", campaign: "AtOH", region: "EU", type: "monster", cards: atoh_cards.monsters},
  {name: "Wizards of Morcar Treasure", campaign: "WoM", region: "EU", type: "treasure", cards: wom_cards.treasure},
  {name: "Wizards of Morcar High Mage Spells", campaign: "WoM", region: "EU", type: "highmage", cards: wom_cards.highmagespells},
  {name: "Wizards of Morcar Necromancer Spells", campaign: "WoM", region: "EU", type: "necromancer", cards: wom_cards.necromancerspells},
  {name: "Wizards of Morcar Storm Master Spells", campaign: "WoM", region: "EU", type: "stormmaster", cards: wom_cards.stormmasterspells},
  {name: "Wizards of Morcar Orc Shaman Spells", campaign: "WoM", region: "EU", type: "orcshaman", cards: wom_cards.orcshamanspells},
  {name: "Wizards of Morcar Spells of Protection", campaign: "WoM", region: "EU", type: "spellofprotection", cards: wom_cards.spellsofprotection},
  {name: "Wizards of Morcar Spells of Detection", campaign: "WoM", region: "EU", type: "spellofdetection", cards: wom_cards.spellsofdetection},
  {name: "Wizards of Morcar Spells of Darkness", campaign: "WoM", region: "EU", type: "spellofdarkness", cards: wom_cards.spellsofdarkness},
  {name: "Wizards of Morcar Men-at-Arms", campaign: "WoM", region: "EU", type: "menatarms", cards: wom_cards.menatarms},
  {name: "Monsters", campaign: "GS", region: "US", type: "monster", cards: us_cards.monsters},
  {name: "Artifacts", campaign: "GS", region: "US", type: "artifact", cards: us_cards.artifacts},
  {name: "Air Spells", campaign: "GS", region: "US", type: "airspell", cards: us_cards.airspells},
  {name: "Earth Spells", campaign: "GS", region: "US", type: "earthspell", cards: us_cards.earthspells},
  {name: "Fire Spells", campaign: "GS", region: "US", type: "firespell", cards: us_cards.firespells},
  {name: "Water Spells", campaign: "GS", region: "US", type: "waterspell", cards: us_cards.waterspells},
  {name: "Chaos Spells", campaign: "GS", region: "US", type: "chaos", cards: us_cards.chaosspells},
  {name: "Treasure", campaign: "GS", region: "US", type: "treasure", cards: us_cards.treasure},
  {name: "Equipment (EU style cards, originally not on cards)", campaign: "GS", region: "US", type: "equipment", cards: us_cards.equipment},
  {name: "Kellar's Keep", campaign: "KK", region: "US", type: "artifact", cards: kk_cards.artifacts},
  {name: "Return of the Witch Lord", campaign: "RotWL", region: "US", type: "artifact", cards: rotwl_cards.artifacts},
  {name: "The Frozen Horror Arftifacts", campaign: "FH", region: "US", type: "artifact", cards: fh_cards.artifacts},
  {name: "The Frozen Horror Chaos Spells", campaign: "FH", region: "US", type: "chaos", cards: fh_cards.chaosspells},
  {name: "The Frozen Horror Treasure", campaign: "FH", region: "US", type: "treasure", cards: fh_cards.treasure},
  {name: "The Frozen Horror Monsters", campaign: "FH", region: "US", type: "monster", cards: fh_cards.monsters},
  {name: "The Frozen Horror Men-at-Arms", campaign: "FH", region: "US", type: "menatarms", cards: fh_cards.menatarms},
  {name: "The Mage of the Mirror Arftifacts", campaign: "MM", region: "US", type: "artifact", cards: mm_cards.artifacts},
  {name: "The Mage of the Mirror Chaos Spells", campaign: "MM", region: "US", type: "chaos", cards: mm_cards.chaosspells},
  {name: "The Mage of the Mirror Elf Spells", campaign: "MM", region: "US", type: "elfspell", cards: mm_cards.elfspells},
  {name: "The Mage of the Mirror Treasure", campaign: "MM", region: "US", type: "treasure", cards: mm_cards.treasure},
  {name: "The Mage of the Mirror Monsters", campaign: "MM", region: "US", type: "monster", cards: mm_cards.monsters},
];
