eu_cards = {
treasure: [
  {title: "Gem!", text: "Tucked into the toe of an old boot you find a valuable Gem. The stone is worth 50 gold coins. Record the money on the back of your character sheet.", image: ""},
  {title: "Gold!", text: "A meagre haul of just 10 gold coins is found in the pocket of a smelly, worn jerkin. Record the money on the back of your character sheet.", image: "gold_eu"},
  {title: "Gold!", text: "A rummage through several items of clothing reveals 20 gold coins. Record the money on the back of your character sheet.", image: "gold_eu"},
  {title: "Gold!", text: "Amidst the clutter, the old rags, the greasy fur robes and soiled blankets, you find 25 gold coins. Record the money on the back of your character sheet.", image: "gold_eu"},
  {title: "Gold!", text: "Foolishly left unhidden lies a small box containing 25 gold coins. Record the money on the back of your character sheet.", image: "gold_eu"},
  {title: "Gold!", text: "You find a loose stone behind which is hidden a small leather pouch wrapped in an old rag. You look inside the pouch and find 50 gold coins. Record the money on the back of your character sheet.", image: "gold_eu"},
  {title: "Gold!", text: "You search and find small amounts of gold hidden in several places. But you lose track of time. Roll one die and multiply the result by ten to see how many gold coins you find. Miss your next go. Record the money on the back of your character sheet.", image: "gold_eu"},
  {title: "Trap!", text: "As you search you unwittingly set off a trap. An arrow shoots out from the wall. You must lose one body point. Return this card to the treasure pile.", image: "hazard1"},
  {title: "Trap!", text: "You feel the gentle pressure of a trip wire against your leg, you spin round … but it is too late. You lose one body point from the crossbow bolt that shoots from the wall. Return this card to the treasure pile.", image: "trap03"},
  {title: "Trap!", text: "The stone beneath your foot begins to give way and all too late you realize it is a trap. You fall into a pit and lose one Body point. You may climb out and move as normal on your next turn. The pit then closes. Return this card to the treasure pile.", image: "hazard2"},
  {title: "Heroic Brew", text: "A leather bag hanging on the wall contains a potion. It is a Heroic Brew. The potion may be taken just before you are about to attack. Any player who drinks the potion will be able to make two attacks instead of one, for one turn only. The card is then discarded.", image: ""},
  {title: "Holy Water", text: "Discarded and forgotten in a corner of the room you find a vial of Holy Water. You may use the Holy Water instead of attacking. It will kill any undead creature: Skeleton, Zombie, Mummy. Discard after use.", image: ""},
  {title: "Jewels!", text: "You find a small wooden box. The box is plain and old but within … it is lined with velvet and contains 50 gold coins' worth of jewels. Record the money on the back of your character sheet.", image: ""},
  {title: "Nothing", text: "Despite a thorough search you find nothing.", image: ""},
  {title: "Potion of Resilience", text: "Amidst a collection of old bottles and earthen jugs you find a small clear vial, a Potion of Resilience. It may be taken at any time. You may then roll two extra combat dice in defence when you next defend. The card is then discarded.", image: "potionofstrength"},
  {title: "Potion of Healing", text: "Enveloped in a bundle of rags you find a small bottle of liquid. You recognise it as a healing potion. You may drink the potion at any time. It will restore up to four lost Body points. The card is then discarded.", image: ""},
  {title: "Potion of Speed", text: "Standing on a shelf you see a dusty bottle. As you wipe it clean, you realize it is a potion of speed. You may drink the potion at any time. It will allow you to roll twice as many dice as usual the next time you move. The card is then discarded.", image: ""},
  {title: "Potion of Strength", text: "You find a small purple bottle. It is a Potion of Strength. You may drink the potion at any time. It will enable you to roll two extra combat dice in attack in your next attack. The card is then discarded.", image: ""},
  {title: "Treasure Horde!", text: "Luck is with you. A small treasure chest you find, hidden under an old fur, contains 100 gold coins. Record the money on the back of your character sheet.", image: ""},
  {title: "Wandering Monster", text: "As you are busy searching, a monster stalks up on you and attacks. The Evil Wizard player may place the wandering monster shown in the Quest Book for this adventure in any square next to you. The monster attacks immediately. Return this card to the treasure pile.", image: ""},
],
artifacts: [
  {title: "Borin's Armour", text: "Borin's Armour allows you to roll four combat dice in defence.", image: ""},
  {title: "Orcs Bane", text: "The sword, Orcs Bane allows you to roll two combat dice in attack. You may attack TWICE if you are fighting Orcs.", image: ""},
  {title: "Spirit Blade", text: "Spirit Blade allows you to roll three combat dice in attack OR four dice in attack against undead creatures: Skeletons, Zombies and Mummies.", image: ""},
  {title: "Talisman of Lore", text: "The Talisman allows you to increase your Mind points by two as long as you have the Talisman in your possession.", image: ""},
  {title: "Wand of Recall", text: "The Wand of Recall allows you to cast two spells instead of one during your turn.", image: ""},
],
equipment: [
  {title: "Battle axe", text: "The Battle axe allows you to roll four combat dice in attack. You may not use a shield when using the Battle axe.", image: "", cost: 400, wizard: false, type: "weapon"},
  {title: "Bracers", text: "The Bracers allows you to roll one extra combat die in defence.", image: "", cost: 200, wizard: true, type: "armour"},
  {title: "Broadsword", text: "The Broadsword allows you to roll three combat dice in attack.", image: "", cost: "250", wizard: false, type: "weapon"},
  {title: "Chain Mail", text: "Chain mail armour allows you to roll three combat dice in defence.", image: "", cost: "450", wizard: false, type: "armour"},
  {title: "Cloak of Protection", text: "The cloak allows you to roll one extra die in defence.", image: "", cost: "350", wizard: true, type: "armour"},
  {title: "Crossbow", text: "The Crossbow allows you to roll three combat dice in attack. You may not use the Crossbow against an opponent who is adjacent to you.", image: "", cost: "350", wizard: false, type: "weapon"},
  {title: "Hand axe", text: "The Hand axe allows you to roll two combat dice in attack. You may also throw the Hand axe but if you do so you lose it.", image: "", cost: "150", wizard: false, type: "weapon"},
  {title: "The Helmet", text: "The helmet gives you one extra combat die in defence.", image: "helmet", cost: "120", wizard: false, type: "armour"},
  {title: "Plate armour", text: "Plate armour allows you to roll four combat dice in defence, BUT You may only roll one die for movement whilst wearing plate armour.", image: "", cost: "850", wizard: false, type: "armour"},
  {title: "The shield", text: "The shield gives you one extra combat die in defence.", image: "shield", cost: "100", wizard: false, type: "armour"},
  {title: "Short sword", text: "The Short sword allows you to roll two combat dice in attack. The Short sword may be used to attack diagonally.", image: "", cost: "150", wizard: false, type: "weapon"},
  {title: "Spear", text: "The Spear allows you to roll two combat dice in attack. The Spear may be used to attack diagonally. You may also throw the Spear but if you do so you lose it.", image: "", cost: "150", wizard: false, type: "weapon"},
  {title: "Staff", text: "The Staff allows you to roll two combat dice in attack. The Staff may be used to attack diagonally.", image: "", cost: "100", type: "weapon"},
  {title: "Tool kit", text: "The tool kit enables you to remove any trap that you find. Roll one combat die. On the roll of a skull the trap goes off and you lose one Body point. Once you have rolled the die the trap is removed.", image: "", cost: "250"},
],
airspells: [
  {title: "Genie", text: "This spell conjures up a Genie who will do one of the following: open any door on the board (the room's contents should be put out) OR attack anyone on the board. He will attack only once with five combat dice. The spell is then discarded.", image: ""},
  {title: "Swift Wind", text: "This spell may be cast on any one player. That player may then roll twice as many dice as normal the next time he moves. The spell is then discarded.", image: ""},
  {title: "Tempest", text: "A small Tempest is created which envelops one monster or player of your choice. That monster or player will then miss his next turn. The spell is then discarded.", image: ""},
],
earthspells: [
  {title: "Heal Body", text: "This spell may be cast on any one player. It will restore up to four Body points that have been lost. The spell is then discarded.", image: ""},
  {title: "Pass through Rock", text: "This spell may be cast on any one player. That player may then move through walls when he next moves. The player may move through as many walls as his movement will allow. The spell is then discarded.", image: ""},
  {title: "Rock Skin", text: "This spell may be cast on any one player. That player may then throw two extra combat dice in defence, until the spell is broken. The spell is broken when that player is wounded. The spell is then discarded.", image: ""},
],
firespells: [
  {title: "Ball of Flame", text: "This spell may be cast at any one monster or player. It will inflict two points of Body damage. The victim may roll two dice. For each shield he rolls he may reduce the damage by one. The spell is then discarded.", image: ""},
  {title: "Courage", text: "This spell may be cast on any one player. That player may then throw two extra dice each time he attacks, until the spell is broken. The spell is broken when there are no more monsters visible to that player. The spell is then discarded.", image: ""},
  {title: "Fire of Wrath", text: "This spell may be cast on any one monster or player, anywhere on the board. It will seek out your enemy and inflict one Body point of damage, unless your opponent can roll a shield on one combat die. The spell is then discarded.", image: ""},
],
waterspells: [
  {title: "Sleep", text: "This spell will put one monster or player to sleep. He may try to defend himself by rolling one die per Mind point. If he rolls a shield he is unaffected. Once asleep he may not defend if attacked. He will awake if he rolls a six at the start of his turn, or if attacked.", image: ""},
  {title: "Veil of Mist", text: "This spell may be cast on any one player. That player may then move unseen through spaces that are occupied by other players or monsters the next time he moves. The spell is then discarded.", image: ""},
  {title: "Water of Healing", text: "This spell may be cast on any one player. It will restore up to four Body points that have been lost. The spell is then discarded.", image: ""},
],
};
us_cards = {
equipment: [
  {title: "Battle Axe", text: "This heavy, double-edged axe gives you the attack strength of 4 combat dice. You may not use a shield when using this weapon.", image: "", cost: "450", wizard: false, type: "weapon"},
  {title: "Broadsword", text: "This wide blade gives you the attack strength of 3 combat dice.", image: "", cost: "250", wizard: false, type: "weapon"},
  {title: "Chain Mail", text: "This light metal armor gives you 1 extra combat die in defense. May be combined with the Helmet and/or Shield.", image: "", cost: "500", wizard: false, type: "armor"},
  {title: "Crossbow", text: "This long-range weapon gives you the attack strength of 3 combat dice. You may fire at any Monster that you can “see.” However, you cannot fire at a Monster that is adjacent to you. You have an unlimited supply of arrows.", image: "", cost: "350", wizard: false, type: "weapon"},
  {title: "Dagger", text: "This sharp knife gives you the attack strength of 1 combat die. A dagger can also be thrown at any Monster that you can “see,” but is lost once it is thrown.", image: "", cost: "25", type: "weapon"},
  {title: "Helmet", text: "This protective headpiece gives you 1 extra combat die in defense.", image: "", cost: "125", wizard: false, type: "armor"},
  {title: "Longsword", text: "This long blade gives you the attack strength of 3 combat dice. Because of its length, the longsword enables you to attack diagonally.", image: "broadsword", cost: "350", wizard: false, type: "weapon"},
  {title: "Plate Mail", text: "This heavy metal armor gives you 2 extra combat dice in defense. However, because it is so heavy, you may only roll 1 red die for movement while wearing it. May be combined with the Helmet and/or Shield.", image: "platearmour", cost: "850", wizard: false, type: "weapon"},
  {title: "Shield", text: "This hand-held armor gives you 1 extra combat die in defense. May not be used with the Battle Axe or the Staff.", image: "", cost: "150", wizard: false, type: "armor"},
  {title: "Shortsword", text: "This short blade gives you the attack strength of 2 combat dice.", image: "", cost: "150", wizard: false, type: "weapon"},
  {title: "Staff", text: "This long, sturdy, wooden staff gives you the attack strength of 1 combat die. Because of its length, the staff enables you to attack diagonally. You may not use a shield when using this weapon.", image: "", cost: "100", type: "weapon"},
  {title: "Tool Kit", text: "Disarm Traps This tool kit gives you a 50% chance to disarm any searched-for-and-found (but unsprung) trap. See rulebook for correct procedure. Before you move, you must announce that you are moving onto the trap square to attempt to disarm and remove the trap. Roll one Combat Die. If a Skull is rolled, the trap is sprung. If a White or Black Shield is rolled, the trap is disarmed and gone forever.", image: "", cost: "250"},
],
artifacts: [
  {title: "Borin's Armor", text: "This magical suit of plate mail allows the wearer to roll four combat dice in defense. Unlike normal plate mail, this mysterious, ultralight metal armor does not slow down its wearer.", image: "", wizard: false, image: "borinsarmour"},
  {title: "Elixir of Life", text: "This small bottle of pearly liquid will bring a dead Hero back to life, restoring all of his Body and Mind Points. This potion can only be used once.", image: ""},
  {title: "Orc's Bane", text: "When using this magical shortsword, you roll two combat dice to attack. You may attack twice if attacking an Orc.", image: "", wizard: false},
  {title: "Ring of Return", text: "When invoked, this magical ring will return all Heroes that the ring wearer can \"see\" to the starting point of the Quest. It can only be used once.", image: ""},
  {title: "Spell Ring", text: "This ring enables the Wizard or Elf to cast one spell two times (not simultaneously). At the beginning of a Quest, the wearer of this ring must declare which of his spells he is storing in the ring.", image: ""},
  {title: "Spirit Blade", text: "This magical broadsword has an eerie handle of carved bone. When using it, roll three combat dice to attack, or roll four combat dice if attacking an undead monster (Skelton, Zombie, or Mummy).", image: "", wizard: false},
  {title: "Talisman of Lore", text: "This magical medallion increases your Mind Points by 1 for as long as it is worn.", image: ""},
  {title: "Wand of Magic", text: "This magical wand allows the Elf or Wizard to cast two separate and different spells on his turn instead of one single spell.", image: ""},
  {title: "Wizard's Cloak", text: "This magical cloak made of shimmery fabric is covered with mystical runes. It can be worn only by the Wizard, giving him one extra combat die in defense.", image: ""},
  {title: "Wizard's Staff", text: "This long ancient staff glows with a soft blue light. It can be used only by the Wizard, giving him the attack strength of two combat dice and the ability to strike diagonally.", image: ""},
],
treasure: [
  {title: "Gem!", text: "Tucked into the toe of an old boot you find a small gem worth 35 gold coins. Record the money on your sheet. Do not return this card to the deck.", image: ""},
  {title: "Gold!", text: "Amidst old rags, tattered fur robes and soiled blankets, you find a collection of 15 gold coins. Record the money on your sheet. Do not return this card to the deck.", image: ""},
  {title: "Gold!", text: "You find a loose stone and tear it from the wall. Behind it you discover a small leather pouch wrapped in an old rag. Peering inside, you find 25 gold coins. Record the money on your sheet. Do not return this card to the deck.", image: ""},
  {title: "Hazard!", text: "While you are searching, a hidden arrow shoots from the wall striking you. You lose 1 Body Point and your turn is over. Return this card to the bottom of the deck.", image: "hazard1"},
  {title: "Hazard!", text: "Suddenly, the stone beneath your feet gives way. You fall into a shallow hole, losing 1 Body Point and ending your turn. You may climb out and move normally on your next turn. Return this card to the bottom of the deck.", image: "hazard2"},
  {title: "Heroic Brew", text: "You are surprised to find a leather bag hanging on the wall. If you drink its contents before you attack, you can make two attacks instead of one. This may only be used once. Do not return this card to the deck.", image: ""},
  {title: "Jewels!", text: "You find a small wooden box. It is simple-looking and very old. Within you discover that it is lined with velvet and contains very small jewels worth 50 gold coins. Record the money on your sheet. Do not return this card to the deck.", image: ""},
  {title: "Potion of Defense", text: "Amidst a collection of old bottles, you find a small vial containing a clear liquid. You can drink this potion at any time, giving you two extra combat dice the next time you defend. This may only be used once. Do not return this card to the deck.", image: ""},
  {title: "Potion of Healing", text: "In a bundle of rags, you find a small bottle of bluish liquid. You can drink this healing potion at any time, restoring the number of Body Points equal to a roll of one red die. You cannot, however, exceed your starting number of Body Points. This may only be used once. Do not return this card to the deck.", image: ""},
  {title: "Potion of Strength", text: "You find a small purple flask. You can drink this strange smelling liquid at any time, enabling you to roll two extra combat dice the next time you attack. This may only be used once. Do not return this card to the deck.", image: ""},
  {title: "Wandering Monster", text: "As you are searching, a monster stalks you and attacks! Zargon places the wandering monster (listed in the Quest Book) on any square next to you. The monster attacks immediately! Return this card to the bottom of the deck.", image: ""},
],
chaosspells: [
  {title: "Ball of Flame", text: "This spell can be cast on any one Hero. It will inflict 2 Body Points of damage. The Hero immediately rolls two red dice. For each 5 or 6 rolled, the damage is reduced by 1 point.", image: ""},
  {title: "Cloud of Chaos", text: "This spell paralyzes all Heroes located in the same room or corridor. A paralyzed Hero is unable to move, attack, or defend himself. The spell can be broken at once or on a future turn by each victim rolling one red die for each of his Mind Points. By rolling a 6, the Hero frees himself.", image: ""},
  {title: "Command", text: "This spell puts any one Hero under Zargon's control. The spell can be broken immediately or on a future turn by the Hero rolling one red die for each of his Mind Points. If a 6 is rolled, the spell is broken. However, until the spell is broken, Zargon, on his turn, can move the Hero as a monster and attack other Heroes.", image: ""},
  {title: "Escape", text: "This spell allows the spellcaster to disappear and instantly telepot to a secret destination known only to Zargon. This \"safe place\" is marked on the Quest Map.", image: ""},
  {title: "Fear", text: "This spell causes any one Hero to become so fearful that his attacks are reduced to one combat die. The spell can be broken by the Hero on a future turn by rolling one red die for each of his Mind Points. If a 6 is rolled, the spell is broken.", image: ""},
  {title: "Firestorm", text: "This spell creates a roomful of fire that inflicts 3 Body Points of damage on all Heroes and monsters in the same room with the spellcaster. The spellcaster is unaffected. All victims immediately roll two red dice. For each 5 or 6 rolled, the damage is reduced by 1 point. Not used in corridors.", image: ""},
  {title: "Lightning Bolt", text: "This spell may be cast in a horizontal, vertical, or diagonal direction. The bolt will travel in a straight line until it strikes a wall or closed door. It will inflict 2 points of Body damage on all Heroes or monsters that stand in its path.", image: "lightning"},
  {title: "Rust", text: "This spell causes any one metal sword or helmet to become so thin, brittle and useless that it can never be used again. Not effective against Artifacts.", image: ""},
  {title: "Sleep", text: "This spell puts any one Hero into a deep sleep. A sleeping Hero is unable to move, attack, or defend himself. The spell can be broken immediately or on a future turn by the Hero rolling one red die for each of his Mind Points. If a 6 is rolled, the spell is broken.", image: ""},
  {title: "Summon Orcs", text: "This spell conjures up a group of Orcs to surround and protect the spellcaster. Roll one red die:<br/>Roll a 1, 2 or 3 = 4 Orcs<br/>Roll a 4 or 5 = 5 Orcs<br/>Roll a 6 = 6 Orcs", image: ""},
  {title: "Summon Undead", text: "This spell conjures up a group of undead to surround and protect the spellcaster. Roll one red die:<br/>Roll a 1 or 2 = 4 Skeletons<br/>Roll a 3 or 4 = 3 Skeletons, 2 Zombies<br/>Roll a 5 or 6 = 2 Zombies, 2 Mummies", image: ""},
  {title: "Tempest", text: "This spell creates a small whirlwind that envelops one Hero of your choice. That Hero will then miss his next turn.", image: ""},
],
airspells: [
  {title: "Genie", text: "This spell conjures up a Genie who will do one of the following: open any door on the board (revealing what lies beyond) OR use 5 combat dice to attack any monster within your line of sight.", image: ""},
  {title: "Swift Wind", text: "This spell may be cast on any one Hero, including yourself. Its powerful burst of energy enables that Hero to roll twice as many red dice as normal the next time he moves.", image: ""},
  {title: "Tempest", text: "This spell creates a small whirlwind that envelops one monster of your choice. That monster will then miss its next turn.", image: ""},
],
earthspells: [
  {title: "Heal Body", text: "This spell may be cast on any one Hero, including yourself. Its magical power will immediately restore up to 4 lost Body Points, but does not give a Hero more than his starting number.", image: ""},
  {title: "Pass Through Rock", text: "This spell can be cast on any one Hero, including yourself. That Hero may then move through walls on his next move. He may move through as many walls as his dice roll allows. Caution! There are shaded areas on each Quest Map which indicate solid rock. If a Hero ends his move in one of these areas, he is trapped forever!", image: ""},
  {title: "Rock Skin", text: "This spell may be cast on any one Hero, including yourself. That Hero may throw one extra combat die when defending. The spell is broken when the Hero suffers 1 point of Body damage.", image: ""},
],
firespells: [
  {title: "Ball of Flame", text: "This spell may be cast on any one monster, enveloping it in a ball of fire. It will inflict 2 Body Points of damage. The monster then rolls two red dice. For each 5 or 6 rolled, the damage is reduced by 1 point.", image: ""},
  {title: "Courage", text: "This spell may be cast on any one Hero, including yourself. The next time that Hero attacks, he may roll two extra combat dice. The spell is broken the moment the Hero can no longer \"see\" a monster.", image: ""},
  {title: "Fire of Wrath", text: "This spell may be cast on any one monster, blasting it with flames. It will inflict 1 Body Point of damage, unless the monster can immediately roll a 5 or 6 using one red die.", image: ""},
],
waterspells: [
  {title: "Sleep", text: "This spell puts a monster into a deep sleep so it cannot move, attack, or defend itself. The spell can be broken at once or on a future turn by a monster rolling one red die for each of its Mind Points. If a 6 is rolled, the spell is broken. May not be used against Mummies, Zombies or Skeletons.", image: ""},
  {title: "Veil of Mist", text: "This spell may be cast on any one Hero, including yourself. On the Hero's next move, he may move unseen through spaces that are occupied by monsters.", image: ""},
  {title: "Water of Healing", text: "This spell may be cast on any one Hero, including yourself. Contact with this revitalizing water will restore up to 4 lost Body Points, but will not give a Hero more than his starting number.", image: ""},
],
};
kk_cards = {
artifacts: [
  {title: "Fire Ring", text: "Protects the wearer from any 2 Chaos fire spells. Ring disappears after wearer has been protected from the second fire spell.", image: ""},
  {title: "Magical Throwing Dagger", text: "Always inflicts 1 Body Point of damage when thrown at a monster a Hero can \"see.\" Monster cannot defend. Dagger is lost once it is thrown.", image: ""},
  {title: "Ball of Flame", text: "This spell may be cast on a monster, enveloping it in a ball of fire. It will inflict 2 Body Points of damage. The monster then rolls two red dice. For each 5 or 6 rolled, the damage is reduced by 1 point.", image: "", type: "scroll"},
  {title: "Courage", text: "This spell may be cast on a Hero, including yourself. The next time that Hero attacks, he may roll two extra combat dice. The spell is broken the moment the Hero can no longer \"see\" a monster.", image: "", type: "scroll"},
  {title: "Fire of Wrath", text: "This spell may be cast on a monster, blasting it with flames. It will inflict 1 Body Point of damage, unless the monster can immediately roll a 5 or 6 using one red die.", image: "", type: "scroll"},
  {title: "Genie", text: "This spell conjures up a Genie who will do one of the following: open any door on the gameboard (revealing what lies beyond), OR use five combat dice to attack a monster within your line of sight.", image: "", type: "scroll"},
  {title: "Heal Body", text: "This spell may be cast on a Hero, including yourself. Its magical power will immediately restore up to 4 lost Body Points, but does not give a Hero more than his starting number.", image: "", type: "scroll"},
  {title: "Rock Skin", text: "This spell may be cast on a Hero, including yourself. That Hero may roll one extra combat die when defending. The spell is broken when the Hero suffers 1 Body Point of damage.", image: "", type: "scroll"},
  {title: "Sleep", text: "This spell puts a monster into a deep sleep so it cannot move, attack, or defend itself. The spell can be broken at once or on a future turn by a monster rolling one red die for each of its Mind Points. If a 6 is rolled, the spell is broken. May not be used against Mummies, Zombies or Skeletons.", image: "", type: "scroll"},
  {title: "Tempest", text: "This spell may be cast on a monster, surrounding it with a small whirlwind. That monster will then miss its next turn.", image: "", type: "scroll"},
],
}
rotwl_cards = {
artifacts: [
  {title: "Anti-poison Quill", text: "Restores any of the owner’s Body Points lost by poisoning if used immediately. May only be used once.", image: ""},
  {title: "Armband of Healing", text: "Restores 2 lost Body Points once per Quest. If the wearer’s Body Points are reduced to zero, use immediately to restore 2 Body Points.", image: ""},
  {title: "Dust of Disappearance", text: "If tossed on any Hero, this dust allows that Hero to move past any monsters encountered on his next turn. May only be used once.", image: ""},
  {title: "Magical Throwing Dagger", text: "Always inflicts 1 Body Point of damage when thrown at a monster a Hero can \"see.\" Monster cannot defend. Dagger is lost once it is thrown.", image: ""},
  {title: "Rabbit Boots", text: "To jump over 1 discovered trap per turn, roll anything but a Black Shield on 1 combat die.", image: ""},
  {title: "Ball of Flame", text: "This spell may be cast on a monster, enveloping it in a ball of fire. It will inflict 2 Body Points of damage. The monster then rolls two red dice. For each 5 or 6 rolled, the damage is reduced by 1 point.", image: "", type: "scroll"},
  {title: "Courage", text: "This spell may be cast on a Hero, including yourself. The next time that Hero attacks, he may roll two extra combat dice. The spell is broken the moment the Hero can no longer \"see\" a monster.", image: "", type: "scroll"},
  {title: "Fire of Wrath", text: "This spell may be cast on a monster, blasting it with flames. It will inflict 1 Body Point of damage, unless the monster can immediately roll a 5 or 6 using one red die.", image: "", type: "scroll"},
  {title: "Genie", text: "This spell conjures up a Genie who will do one of the following: open any door on the gameboard (revealing what lies beyond), OR use five combat dice to attack a monster within your line of sight.", image: "", type: "scroll"},
  {title: "Pass Through Rock", text: "This spell may be cast on a Hero, including yourself. That Hero may then move through walls on his next move. He may move through as many walls as his dice roll allows. Caution! There are shaded areas on each Quest Map which indicate solid rock. If a Hero ends his move in one of these areas, he is trapped forever!", image: "", type: "scroll"},
],
}
sets = [
  {name: "Quest Treasure", region: "EU", type: "artifact", cards: eu_cards.artifacts},
  {name: "Air Spells", region: "EU", type: "airspell", cards: eu_cards.airspells},
  {name: "Earth Spells", region: "EU", type: "earthspell", cards: eu_cards.earthspells},
  {name: "Fire Spells", region: "EU", type: "firespell", cards: eu_cards.firespells},
  {name: "Water Spells", region: "EU", type: "waterspell", cards: eu_cards.waterspells},
  {name: "Treasure", region: "EU", type: "treasure", cards: eu_cards.treasure},
  {name: "Equipment", region: "EU", type: "equipment", cards: eu_cards.equipment},
  {name: "Artifacts", region: "US", type: "artifact", cards: us_cards.artifacts},
  {name: "Air Spells", region: "US", type: "airspell", cards: us_cards.airspells},
  {name: "Earth Spells", region: "US", type: "earthspell", cards: us_cards.earthspells},
  {name: "Fire Spells", region: "US", type: "firespell", cards: us_cards.firespells},
  {name: "Water Spells", region: "US", type: "waterspell", cards: us_cards.waterspells},
  {name: "Chaos Spells", region: "US", type: "chaos", cards: us_cards.chaosspells},
  {name: "Treasure", region: "US", type: "treasure", cards: us_cards.treasure},
  {name: "Equipment (EU style cards, originally not on cards)", region: "US", type: "equipment", cards: us_cards.equipment},
  {name: "Kellar's Keep", region: "US", type: "artifact", cards: kk_cards.artifacts},
  {name: "Return of the Witch Lord", region: "US", type: "artifact", cards: rotwl_cards.artifacts},
];
