cards_my = {
artifacts: [
  {title: "Borin's Armour", text: "You may roll 4 dice in defence.", image: "", type: "armour"},
  {title: "Orcs Bane", text: "You may roll 2 dice in attack.<br/>Each round you may additionally attack an Orc.", image: "", type: "weapon"},
  {title: "Spirit Blade", text: "You may roll 3 dice in attack, 4 against undead creatures.", image: "", type: "weapon"},
  {title: "Wand of Recall", text: "Each round you may additionally cast a spell.", image: ""},
  {title: "Talisman of Lore", text: "When found and at the beginning of each quest you get the Dark Spells.", image: ""},
],
treasure: [
  {title: "Potion of Healing", text: "Recover all lost Boy points.", image: "", type: "potion"},
  {title: "Potion of Healing", text: "Recover all lost Boy points.", image: "", type: "potion"},
  {title: "Potion of Speed", text: "Immediately perform a movement.", image: "", type: "potion"},
  {title: "Potion of Magical Aptitude", text: "Immediately cast a spell.", type: "potion"},
  {title: "Heroic Brew", text: "Immediately perform an attack.", image: "", type: "potion"},
  {title: "Holy Water", text: "Kill one adjacent undead creature.", image: "", type: "potion"},
  {title: "Potion of Strength", text: "Until the end of your turn you may roll 4 dice in attack.", image: "", type: "potion"},
  {title: "Potion of Resilience", text: "Until the end of your turn you may ignore all Body points you lose.", image: "potionofdefense", type: "potion"},
  {title: "Treasure Horde!", text: "Luck is with you. A small treasure chest you find, hidden under an old fur, contains 100 gold coins.", image: "", type: "100 gold"},
  {title: "Gem!", text: "Tucked into the toe of an old boot you find a valuable Gem. The stone is worth 50 gold coins.", image: "", type: "50 gold"},
  {title: "Jewels!", text: "You find a small wooden box. The box is plain and old but within … it is lined with velvet and contains 50 gold coins' worth of jewels.", image: "", type: "50 gold"},
  {title: "Gold!", text: "A meagre haul of just 25 gold coins is found in the pocket of a smelly, worn jerkin.", image: "gold_eu", type: "25 gold"},
  {title: "Gold!", text: "A rummage through several items of clothing reveals 25 gold coins.", image: "gold_eu", type: "25 gold"},
  {title: "Gold!", text: "Amidst the clutter, the old rags, the greasy fur robes and soiled blankets, you find 25 gold coins.", image: "gold_eu", type: "25 gold"},
  {title: "Gold!", text: "Foolishly left unhidden lies a small box containing 25 gold coins.", image: "gold_eu", type: "25 gold"},
  {title: "Gold!", text: "You find a loose stone behind which is hidden a small leather pouch wrapped in an old rag. You look inside the pouch and find 25 gold coins.", image: "gold_eu", type: "25 gold"},
  {title: "Gold!", text: "You search and find 25 gold coins hidden in several places.", image: "gold_eu", type: "25 gold"},
  {title: "Nothing", text: "Despite a thorough search you find nothing.", image: ""},
  {title: "Trap!", text: "As you search you unwittingly set off a trap. An arrow shoots out from the wall. You must lose one body point.", image: "hazard1"},
  {title: "Trap!", text: "You feel the gentle pressure of a trip wire against your leg, you spin round … but it is too late. You lose one body point from the crossbow bolt that shoots from the wall.", image: "hazard1"},
  {title: "Trap!", text: "The stone beneath your foot begins to give way and all too late you realize it is a trap. You fall into a pit and lose one Body point. You may climb out and move as normal on your next turn.", image: "trap03"},
  {title: "Wandering Monster", text: "As you are busy searching a monster stalks up on you and attacks.", image: ""},
  {title: "Wandering Monster", text: "As you are busy searching a monster stalks up on you and attacks.", image: ""},
  {title: "Wandering Monster", text: "As you are busy searching a monster stalks up on you and attacks.", image: ""},
  {title: "Wandering Monster", text: "As you are busy searching a monster stalks up on you and attacks.", image: ""},
  {title: "Wandering Monster", text: "As you are busy searching a monster stalks up on you and attacks.", image: ""},
],
earthspells: [
  {title: "Heal Body", text: "The target recovers all lost Body points.", image: ""},
  {title: "Pass through Rock", text: "Until the end of his turn the target may move through walls.", image: ""},
  {title: "Rock Skin", text: "Until the end of the quest the target may roll 3 dice in defence.", image: ""},
  {title: "Impure Reincarnation", text: "Place up to 3 zombies on empty squares in your area. The zombies are under your control and may move and attack at once.", image: "summonundead", type: "chaos spell", set: "chaos"},
],
firespells: [
  {title: "Fire of Wrath", text: "A target anywhere on the board rolls 2 dice. For each skull rolled he loses one Body point.", image: ""},
  {title: "Ball of Flame", text: "The target rolls 3 dice. For each skull rolled he loses one Body point.", image: ""},
  {title: "Courage", text: "The target may immediately attack with 4 dice.", image: ""},
  {title: "Firestorm", text: "All models in your area except you suffer a loss of one Body point.", image: "", type: "chaos spell", set: "chaos"},
],
waterspells: [
  {title: "Sleep", text: "The target rolls one die per Mind point. If he doesn't roll a shield he falls asleep until he is attacked or rolls a six at the start of his turn. While asleep he may not defend if attacked.", image: ""},
  {title: "Veil of Mist", text: "Until the end of his turn the target may move through squares occupied by other miniatures without asking for permission.", image: ""},
  {title: "Water of Healing", text: "The target recovers all lost body points.", image: ""},
  {title: "Cloud of Chaos", text: "This spell paralyzes all Heroes located in the same room or corridor. A paralyzed Hero is unable to move, attack, or defend himself. The spell can be broken at once or on a future turn by each victim rolling one red die for each of his Mind Points. By rolling a 6, the Hero frees himself.", image: "", type: "utimate spell", set: "chaos"},
],
airspells: [
  {title: "Genie", text: "You conjure up a Genie on an empty square anywhere on the board who will either open a door or attack with 5 dice. The Genie then disappears.", image: ""},
  {title: "Swift Wind", text: "Roll 2 dice and move the target up to the rolled distance.", image: ""},
  {title: "Tempest", text: "Until the end of his turn the target may neither move, search, attack nor cast spells.", image: ""},
  {title: "Lightning Bolt", text: "You send out a lightning bolt along a horizontal, vertical or diagonal line until it strikes a wall or closed door. Any model standing in its path loses one Body point.", image: "lightning", type: "chaos spell", set: "chaos"},
],
darkspells: [
  {title: "Madness", text: "Each round at the beginning of his turn the target rolls one die. On a skull you control the target for this turn.", image: "command"},
  {title: "Summon Skeleton", text: "Place a skeleton on an empty square in your area. The skeleton is under your control and may move and attack at once.", image: "callskeleton", set: "necromancer"},
  {title: "Fear", text: "The target is so fearful that his attacks are reduced to one die.", image: ""},
  {title: "Escape", text: "You teleport to an empty square anywhere on the board.", image: "", type: "chaos spell"},
],
}
sets_my = [
  {name: "Quest Treasure", campaign: "GS", region: "EU", type: "artifact", cards: cards_my.artifacts},
  {name: "Air Spells", campaing: "GS", region: "EU", type: "airspell", cards: cards_my.airspells},
  {name: "Earth Spells", campaign: "GS", region: "EU", type: "earthspell", cards: cards_my.earthspells},
  {name: "Fire Spells", campaign: "GS", region: "EU", type: "firespell", cards: cards_my.firespells},
  {name: "Water Spells", campaign: "GS", region: "EU", type: "waterspell", cards: cards_my.waterspells},
  {name: "Dark Spells", campaign: "GS", region: "EU", type: "chaos", cards: cards_my.darkspells},
  {name: "Treasure", campaign: "GS", region: "EU", type: "treasure", cards: cards_my.treasure},
]
sets["My"] = sets_my
