cards_my = {
artifacts: [
  {title: "Borin's Armour", text: "You may roll 4 dice in defence.", image: "", type: "armour"},
  {title: "Spirit Blade", text: "You may roll 3 dice in attack, 4 against undead creatures.", image: "", type: "weapon"},
  {title: "Orcs Bane", text: "You may roll 2 dice in attack.<br/>Each turn you may attack an Orc as an extra action.", image: "", type: "weapon"},
  {title: "Wand of Recall", text: "Each turn you may cast a spell as an extra action.", image: ""},
  {title: "Talisman of Lore", text: "Increases your mind points by 2 as long as it is in your possession.", image: ""},
],
treasure: [
  {title: "Potion of Healing", text: "Restore up to 4 lost Body points.", image: "", type: "potion"},
  {title: "Potion of Healing", text: "Restore up to 4 lost Body points.", image: "", type: "potion"},
  {title: "Potion of Speed", text: "You get one extra movement.", image: "", type: "potion"},
  {title: "Heroic Brew", text: "You get one extra attack.", image: "", type: "potion"},
  {title: "Holy Water", text: "Kill one adjacent undead creature.", image: "", type: "potion"},
  {title: "Potion of Strength", text: "Until the end of your turn you may roll 4 dice in attack.", image: "", type: "potion"},
  {title: "Potion of Resilience", text: "Until the beginning of your next turn you may ignore all Body points you lose.", image: "potionofdefense", type: "potion"},
  {title: "Treasure Horde!", text: "100 gold coins.", image: "", type: "100 gold"},
  {title: "Gem!", text: "Worth 50 gold coins.", image: "", type: "50 gold"},
  {title: "Jewels!", text: "Worth 50 gold coins.", image: "", type: "50 gold"},
  {title: "Gold!", text: "25 gold coins.", image: "gold_eu", type: "25 gold"},
  {title: "Gold!", text: "25 gold coins.", image: "gold_eu", type: "25 gold"},
  {title: "Gold!", text: "25 gold coins.", image: "gold_eu", type: "25 gold"},
  {title: "Gold!", text: "25 gold coins.", image: "gold_eu", type: "25 gold"},
  {title: "Gold!", text: "25 gold coins.", image: "gold_eu", type: "25 gold"},
  {title: "Gold!", text: "25 gold coins.", image: "gold_eu", type: "25 gold"},
  {title: "Nothing", text: "", image: ""},
  {title: "Trap!", text: "You lose one body point.", image: "hazard1"},
  {title: "Trap!", text: "You lose one body point.", image: "hazard1"},
  {title: "Trap!", text: "You lose one body point.", image: "trap03"},
  {title: "Wandering Monster", text: "A monster stalks up on you and attacks.", image: ""},
  {title: "Wandering Monster", text: "A monster stalks up on you and attacks.", image: ""},
  {title: "Wandering Monster", text: "A monster stalks up on you and attacks.", image: ""},
  {title: "Wandering Monster", text: "A monster stalks up on you and attacks.", image: ""},
  {title: "Wandering Monster", text: "A monster stalks up on you and attacks.", image: ""},
],
earthspells: [
  {title: "Heal Body", text: "The target restores up to 4 lost Body points.", image: "", type: "Earth Spell"},
  {title: "Pass through Rock", text: "For one turn the target may move through walls.", image: "", type: "Earth Spell"},
  {title: "Rock Skin", text: "The target may roll 4 dice in defence until he loses a Body point.", image: "", type: "Earth Spell"},
  ],
firespells: [
  {title: "Fire of Wrath", text: "A target anywhere on the board loses 1 body point, which he may defend against normally.", image: "", type: "Fire Spell"},
  {title: "Ball of Flame", text: "The target loses 2 body points, which he may defend against normally.", image: "", type: "Fire Spell"},
  {title: "Courage", text: "The target gets one extra attack.", image: "", type: "Fire Spell"},
],
waterspells: [
  {title: "Sleep", text: "The target rolls one die per Mind point. If he doesn't roll a shield he falls asleep until he is attacked or rolls a six at the start of his turn. While asleep he may not defend if attacked.", image: "", type: "Water Spell"},
  {title: "Veil of Mist", text: "For one turn the target may move through squares occupied by other heores or monsters without asking for permission.", image: "", type: "Water Spell"},
  {title: "Water of Healing", text: "The target restores up to 4 lost body points.", image: "", type: "Water Spell"},
],
airspells: [
  {title: "Genie", text: "A genie appears and will either open any door (revealing what lies behind) OR attack anyone on the board once with 5 dice. ", image: "", type: "Air Spell"},
  {title: "Swift Wind", text: "The target gets one extra movement.", image: "", type: "Air Spell"},
  {title: "Tempest", text: "The target misses his next turn.", image: "", type: "Air Spell"},
],
darkspells: [
  {title: "Madness", text: "Each round at the beginning of his turn the target rolls one die. On a skull you control the target for this turn.", image: "command"},
  {title: "Summon Skeleton", text: "Place a skeleton on an empty square in your area. The skeleton is under your control and may move and attack at once.", image: "callskeleton", set: "necromancer"},
  {title: "Fear", text: "The target is so fearful that his attacks are reduced to one die.", image: ""},
  {title: "Fire of Wrath Commercial", text: "This spell may be cast on any object or door in the same Room or Passage. The object and anything in it will then be destroyed. The spell may not be cast on Monsters or Players.", image: "fireofwrath"},
],
}
sets_my = [
  {name: "Quest Treasure", campaign: "GS", region: "EU", type: "artifact", cards: cards_my.artifacts},
  {name: "Air Spells", campaing: "GS", region: "EU", type: "airspell", cards: cards_my.airspells},
  {name: "Earth Spells", campaign: "GS", region: "EU", type: "earthspell", cards: cards_my.earthspells},
  {name: "Fire Spells", campaign: "GS", region: "EU", type: "firespell", cards: cards_my.firespells},
  {name: "Water Spells", campaign: "GS", region: "EU", type: "waterspell", cards: cards_my.waterspells},
  {name: "Treasure", campaign: "GS", region: "EU", type: "treasure", cards: cards_my.treasure},
]
sets["my"] = sets_my
